[package]
name = "kv-crud-sqlite"
version = "0.1.0"
authors = ["Marcin Radoszewski <moriturius@gmail.com>"]
edition = "2018"

[dependencies]
kv-crud-core = "0.1"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sqlite = "0.24.0"
